language: android

sudo: false
env:
  global:
    - ANDROID_ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.3

    # The SDK version used to compile your project
    - android-23

    - extra-android-m2repository
